#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Stage A owner wizard: Sentry DSN + TestFlight upload + dSYM upload.
# No value is written to .env, a file, or a GitHub secret: everything stays in
# this script's memory and is gone when it exits. Never commit this wizard's
# output; it holds none.

ENV_FILE=/dev/null
REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$REPO_ROOT"

TOTAL_STAGES=8
LOG=$(mktemp "${TMPDIR:-/tmp}/tradeready-stage-a-wizard.XXXXXX")
trap 'rm -f "$LOG"' EXIT

banner "TradeReady Stage A: Sentry + TestFlight upload (owner steps)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the repo is ready"
say "Running the offline Stage A preflight (read-only)."
if sh native/run-phase-12-stage-preflight.sh --stage A 2>&1 | tee "$LOG" | grep -E "^(FAIL|READY|NOT READY)"; then :; fi
if grep -q "^FAIL" "$LOG" || grep -q "^NOT READY" "$LOG"; then
  warn "The preflight has FAIL lines. Stop here and ask for help before uploading."
  exit 1
fi
say "No FAIL lines. Good."
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sentry: DSN"
say "The DSN tells the app where to send crash reports."
open_url "https://tradeready-3r.sentry.io/settings/projects/tradeready-ios/keys/"
step "On that page, copy the DSN under 'Default' (it starts with https://)."
note "Nothing you type here is shown on screen or saved."
while :; do
  ask_secret TRADEREADY_SENTRY_DSN "Paste the DSN, then press Enter:"
  if [[ "$TRADEREADY_SENTRY_DSN" =~ ^https://[^@/]+@[^/]+/[0-9]+$ ]]; then
    say "Looks like a valid DSN."; break
  fi
  warn "That doesn't look like a DSN (expected https://KEY@HOST/NUMBER). Try again."
done
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sentry: auth token (for crash symbols)"
step "You already created an auth token in Sentry (Settings → Auth Tokens)."
say "If you can't find it, create a new one there and copy it now."
open_url "https://tradeready-3r.sentry.io/settings/auth-tokens/"
ask_secret SENTRY_AUTH_TOKEN "Paste the auth token, then press Enter:"
if [[ -z "$SENTRY_AUTH_TOKEN" ]]; then
  warn "No token entered. The crash-symbol step will be skipped, so crashes won't be readable."
fi
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: API key"
say "We need three values from one API key."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the 'Team Keys' tab."
step "The Issuer ID is shown at the top of the page. Copy it."
ask_secret ASC_ISSUER_ID "Paste the Issuer ID:"
step "If you have no key yet: click +, name it tradeready-upload, access 'App Manager', Generate."
step "Click Download on that key's row (one time only). Save it in ~/Documents."
step "The Key ID is the 10-character code on the key's row. Copy it."
ask_secret ASC_KEY_ID "Paste the Key ID:"
while :; do
  ask ASC_KEY_PATH "Path to the downloaded .p8 file (you can drag the file into this window):"
  ASC_KEY_PATH=${ASC_KEY_PATH//\\ / }; ASC_KEY_PATH=${ASC_KEY_PATH%\'}; ASC_KEY_PATH=${ASC_KEY_PATH#\'}
  ASC_KEY_PATH=${ASC_KEY_PATH/#\~/$HOME}
  if [[ -f "$ASC_KEY_PATH" && "$ASC_KEY_PATH" == *.p8 ]]; then
    case "$ASC_KEY_PATH" in "$REPO_ROOT"/*) warn "That file is inside the project folder. Move it outside so it can't be committed."; continue;; esac
    say "Found the key file."; break
  fi
  warn "No .p8 file at that path. Try again."
done
if [[ -z "$ASC_KEY_ID" || -z "$ASC_ISSUER_ID" ]]; then
  warn "Key ID or Issuer ID is empty. Re-run the wizard."; exit 1
fi
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Pick the build number"
say "Each upload of version 2.0.0 needs a build number higher than every earlier one."
open_url "https://appstoreconnect.apple.com/apps"
step "Open TradeReady, then the TestFlight tab, then Builds."
step "If no 2.0.0 build is listed, use 1. Otherwise use one more than the highest."
while :; do
  ask BUILD_NUMBER "Build number:"
  [[ "$BUILD_NUMBER" =~ ^[0-9]+$ && "$BUILD_NUMBER" -ge 1 ]] && break
  warn "Enter a whole number, 1 or higher."
done
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Practice run (uploads nothing)"
say "Checking the upload command with your DSN. Nothing is built or sent."
if TRADEREADY_SENTRY_DSN="$TRADEREADY_SENTRY_DSN" sh native/phase-12-testflight-upload.sh \
     --version 2.0.0 --build "$BUILD_NUMBER" >"$LOG" 2>&1 \
   && grep -q "variable is set; value not shown" "$LOG"; then
  say "Practice run passed, and the DSN was picked up."
else
  warn "Practice run failed:"; sed -n '1,40p' "$LOG"; exit 1
fi
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Build and upload to TestFlight (real)"
warn "This builds version 2.0.0 (build $BUILD_NUMBER) and uploads it to App Store Connect."
say "It takes several minutes. It cannot be undone, but the build number is then used up."
if ! confirm "Upload now?"; then say "Stopped. Nothing was uploaded."; exit 0; fi
set +e
ASC_KEY_ID="$ASC_KEY_ID" ASC_ISSUER_ID="$ASC_ISSUER_ID" ASC_KEY_PATH="$ASC_KEY_PATH" \
TRADEREADY_SENTRY_DSN="$TRADEREADY_SENTRY_DSN" \
  sh native/phase-12-testflight-upload.sh --version 2.0.0 --build "$BUILD_NUMBER" \
  --execute --i-am-the-owner 2>&1 | tee "$LOG"
upload_status=${PIPESTATUS[0]}
set -e
if [[ "$upload_status" -ne 0 ]]; then
  warn "The upload failed (see above). Fix that, then re-run this wizard."
  exit 1
fi
ARCHIVE_PATH=$(sed -n 's/^Uploaded\. Archive (for the Sentry dSYM upload): //p' "$LOG" | tail -n1)
if [[ -z "$ARCHIVE_PATH" || ! -d "$ARCHIVE_PATH" ]]; then
  warn "Uploaded, but I couldn't find the archive path. Crash symbols can't be uploaded automatically."
  exit 1
fi
say "Uploaded. Archive: $ARCHIVE_PATH"
APP_PLIST="$ARCHIVE_PATH/Products/Applications/TradeReadyNative.app/Info.plist"
DSN_HEAD=$(plutil -extract TradeReadySentryDSN raw "$APP_PLIST" 2>/dev/null | cut -c1-8 || true)
if [[ "$DSN_HEAD" == "https://" ]]; then
  say "Checked: the built app contains the Sentry DSN."
else
  warn "The built app does NOT contain a valid DSN (found: '${DSN_HEAD:-nothing}'). Crash reporting would be off. Tell your agent before using this build."
fi
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Upload crash symbols, then TestFlight"
if [[ -n "$SENTRY_AUTH_TOKEN" ]]; then
  if ! command -v sentry-cli >/dev/null 2>&1; then
    warn "sentry-cli isn't installed. In another terminal run: brew install sentry-cli"
    pause "Press Enter once it's installed"
  fi
  if SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN" sh native/scripts/upload-sentry-dsyms.sh "$ARCHIVE_PATH"; then
    say "Crash symbols uploaded."
  else
    warn "Crash symbol upload failed. Re-run it by hand later with the archive path above."
  fi
else
  warn "Skipped crash symbols (no token). Upload them later from: $ARCHIVE_PATH"
fi
say ""
say "Last, in App Store Connect:"
open_url "https://appstoreconnect.apple.com/apps"
step "TradeReady → TestFlight → wait until build 2.0.0 ($BUILD_NUMBER) shows 'Processed'."
step "Add your internal testing group to the build."
say ""
say "Then tell your agent: 'TF-INT done, build 2.0.0 ($BUILD_NUMBER)'. It will record the"
say "decision-log rows. Close this terminal window afterwards to clear all pasted values."
pause "Press Enter to finish"
unset TRADEREADY_SENTRY_DSN SENTRY_AUTH_TOKEN ASC_KEY_ID ASC_ISSUER_ID ASC_KEY_PATH

finish
