#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

"$ROOT_DIR/native/run-domain-tests.sh"
sh "$ROOT_DIR/native/run-canonical-tests.sh"
"$ROOT_DIR/native/run-snapshot-tests.sh"
"$ROOT_DIR/native/run-repository-tests.sh"
"$ROOT_DIR/native/run-money-card-tests.sh"
"$ROOT_DIR/native/run-expense-editor-tests.sh"
"$ROOT_DIR/native/run-mileage-log-tests.sh"
"$ROOT_DIR/native/run-pricebook-ui-tests.sh"
"$ROOT_DIR/native/run-export-import-ui-tests.sh"
"$ROOT_DIR/native/run-phase9-qualification-tests.sh"
"$ROOT_DIR/native/run-legacy-import-tests.sh"
"$ROOT_DIR/native/run-migration-coordinator-tests.sh"
"$ROOT_DIR/native/run-auxiliary-activation-tests.sh"
"$ROOT_DIR/native/run-authenticated-identity-tests.sh"
"$ROOT_DIR/native/run-build-environment-tests.sh"
"$ROOT_DIR/native/run-supabase-auth-tests.sh"
"$ROOT_DIR/native/run-initial-sync-tests.sh"
"$ROOT_DIR/native/run-delta-sync-tests.sh"
"$ROOT_DIR/native/run-mutation-queue-tests.sh"
sh "$ROOT_DIR/native/run-record-deletion-tests.sh"
"$ROOT_DIR/native/run-mutation-push-tests.sh"
"$ROOT_DIR/native/run-sync-coordinator-tests.sh"
sh "$ROOT_DIR/native/run-background-refresh-tests.sh"
sh "$ROOT_DIR/native/run-job-photo-transfer-tests.sh"
"$ROOT_DIR/native/run-two-device-convergence-tests.sh"
"$ROOT_DIR/native/run-sync-backfill-tests.sh"
"$ROOT_DIR/native/run-subscription-tests.sh"
"$ROOT_DIR/native/run-account-deletion-tests.sh"
"$ROOT_DIR/native/run-typed-account-state-tests.sh"
"$ROOT_DIR/native/run-app-group-pending-open-url-tests.sh"
  "$ROOT_DIR/native/run-appointment-messaging-tests.sh"
  "$ROOT_DIR/native/run-appointment-notification-tests.sh"
sh "$ROOT_DIR/native/run-estimate-approval-link-tests.sh"
sh "$ROOT_DIR/native/run-estimate-pdf-tests.sh"
sh "$ROOT_DIR/native/run-estimate-delivery-tests.sh"
sh "$ROOT_DIR/native/run-estimate-message-draft-tests.sh"
sh "$ROOT_DIR/native/run-estimate-follow-up-tests.sh"
sh "$ROOT_DIR/native/run-estimate-follow-up-notification-tests.sh"
sh "$ROOT_DIR/native/run-review-request-tests.sh"
sh "$ROOT_DIR/native/run-change-order-tests.sh"
sh "$ROOT_DIR/native/run-job-profitability-tests.sh"
sh "$ROOT_DIR/native/run-change-order-approval-link-tests.sh"
sh "$ROOT_DIR/native/run-customer-contact-action-tests.sh"
"$ROOT_DIR/native/run-widget-action-replay-tests.sh"
"$ROOT_DIR/native/run-business-rules-tests.sh"
"$ROOT_DIR/native/run-recurring-job-tests.sh"
"$ROOT_DIR/native/run-adapter-tests.sh"
"$ROOT_DIR/native/run-customer-identity-tests.sh"
sh "$ROOT_DIR/native/run-address-lookup-tests.sh"
sh "$ROOT_DIR/native/run-global-search-tests.sh"
sh "$ROOT_DIR/native/run-interaction-state-tests.sh"
sh "$ROOT_DIR/native/run-job-list-tests.sh"
sh "$ROOT_DIR/native/run-invoice-list-tests.sh"
sh "$ROOT_DIR/native/run-invoice-editing-tests.sh"
sh "$ROOT_DIR/native/run-payment-link-tests.sh"
sh "$ROOT_DIR/native/run-stripe-connect-tests.sh"
sh "$ROOT_DIR/native/run-invoice-pdf-tests.sh"
sh "$ROOT_DIR/native/run-outreach-tests.sh"
sh "$ROOT_DIR/native/run-bulk-invoice-tests.sh"
sh "$ROOT_DIR/native/run-recurring-invoice-tests.sh"
sh "$ROOT_DIR/native/run-invoice-notification-tests.sh"
"$ROOT_DIR/native/run-invoice-from-job-tests.sh"
sh "$ROOT_DIR/native/run-invoice-delivery-tests.sh"
sh "$ROOT_DIR/native/run-time-tracking-tests.sh"
sh "$ROOT_DIR/native/run-confirmation-tests.sh"
"$ROOT_DIR/native/run-store-integration-tests.sh"
"$ROOT_DIR/native/run-phase-3-device-preflight-tests.sh"
"$ROOT_DIR/native/run-phase-4-device-preflight-tests.sh"
(cd "$ROOT_DIR/backend-workers" && npm test)
